// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RNN.Models;

namespace RNN.Migrations
{
    [DbContext(typeof(RNNContext))]
    [Migration("20191022163527_u6")]
    partial class u6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RNN.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("GroupingId");

                    b.Property<string>("HeadLine");

                    b.Property<string>("Img");

                    b.Property<bool>("IsFeatured");

                    b.Property<string>("Paragraph");

                    b.Property<int?>("TitleId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GroupingId");

                    b.HasIndex("TitleId");

                    b.ToTable("Article");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Article");
                });

            modelBuilder.Entity("RNN.Models.ArticleToTopic", b =>
                {
                    b.Property<int>("TopicId");

                    b.Property<int>("ArticleId");

                    b.HasKey("TopicId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleToTopics");

                    b.HasData(
                        new { TopicId = 1, ArticleId = 1 },
                        new { TopicId = 2, ArticleId = 2 },
                        new { TopicId = 3, ArticleId = 3 },
                        new { TopicId = 4, ArticleId = 4 },
                        new { TopicId = 5, ArticleId = 5 },
                        new { TopicId = 6, ArticleId = 6 },
                        new { TopicId = 7, ArticleId = 7 },
                        new { TopicId = 1, ArticleId = 8 },
                        new { TopicId = 2, ArticleId = 9 },
                        new { TopicId = 3, ArticleId = 10 },
                        new { TopicId = 4, ArticleId = 11 },
                        new { TopicId = 1, ArticleId = 12 },
                        new { TopicId = 2, ArticleId = 13 },
                        new { TopicId = 1, ArticleId = 14 },
                        new { TopicId = 2, ArticleId = 14 },
                        new { TopicId = 3, ArticleId = 15 },
                        new { TopicId = 4, ArticleId = 16 },
                        new { TopicId = 5, ArticleId = 17 },
                        new { TopicId = 6, ArticleId = 18 },
                        new { TopicId = 7, ArticleId = 19 },
                        new { TopicId = 1, ArticleId = 20 }
                    );
                });

            modelBuilder.Entity("RNN.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new { Id = 1, Name = "Autho1" }
                    );
                });

            modelBuilder.Entity("RNN.Models.Grouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rank");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Grouping");

                    b.HasData(
                        new { Id = 1, Name = "Grouping 1", Rank = 1 },
                        new { Id = 2, Name = "Grouping 2", Rank = 2 },
                        new { Id = 3, Name = "Grouping 3", Rank = 3 },
                        new { Id = 4, Name = "Grouping 4", Rank = 4 }
                    );
                });

            modelBuilder.Entity("RNN.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new { Id = 1, Name = "Editorial" },
                        new { Id = 2, Name = "Opinion" },
                        new { Id = 3, Name = "UK News" },
                        new { Id = 4, Name = "UK Politics" }
                    );
                });

            modelBuilder.Entity("RNN.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new { Id = 1, Name = "Topic 1" },
                        new { Id = 2, Name = "Topic 2" },
                        new { Id = 3, Name = "Topic 3" },
                        new { Id = 4, Name = "Topic 4" },
                        new { Id = 5, Name = "Topic 5" },
                        new { Id = 6, Name = "Topic 6" },
                        new { Id = 7, Name = "Topic 7" },
                        new { Id = 8, Name = "Topic 8" },
                        new { Id = 9, Name = "Topic 9" },
                        new { Id = 10, Name = "Topic 10" },
                        new { Id = 11, Name = "Topic 11" },
                        new { Id = 12, Name = "Topic 12" },
                        new { Id = 13, Name = "Topic 13" },
                        new { Id = 14, Name = "Topic 14" }
                    );
                });

            modelBuilder.Entity("RNN.Models.Editorial", b =>
                {
                    b.HasBaseType("RNN.Models.Article");


                    b.ToTable("Editorial");

                    b.HasDiscriminator().HasValue("Editorial");

                    b.HasData(
                        new { Id = 12, AuthorId = 1, Body = "", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Boris Johnson under fire over row with partner as top Tories raise fears", Img = "editorial.jpg", IsFeatured = true, Paragraph = "Leadership campaign falters as he refuses to respond to questions at hustings about late-night argument with Carrie Symonds", TitleId = 1, Url = "" },
                        new { Id = 13, AuthorId = 1, Body = "", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "MPs debate Boris Johnson's deal as People's Vote march sets off – live news", Img = "editorial.jpg", IsFeatured = true, Paragraph = "Leadership campaign falters as he refuses to respond to questions at hustings about late-night argument with Carrie Symonds", TitleId = 2, Url = "" }
                    );
                });

            modelBuilder.Entity("RNN.Models.News", b =>
                {
                    b.HasBaseType("RNN.Models.Article");


                    b.ToTable("News");

                    b.HasDiscriminator().HasValue("News");
                });

            modelBuilder.Entity("RNN.Models.Opinion", b =>
                {
                    b.HasBaseType("RNN.Models.Article");


                    b.ToTable("Opinion");

                    b.HasDiscriminator().HasValue("Opinion");

                    b.HasData(
                        new { Id = 14, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 1", Img = "nature.jpg", IsFeatured = true, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 },
                        new { Id = 15, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 2", Img = "nature.jpg", IsFeatured = true, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 },
                        new { Id = 16, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 3", Img = "nature.jpg", IsFeatured = true, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 },
                        new { Id = 17, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 4", Img = "nature.jpg", IsFeatured = false, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 },
                        new { Id = 18, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 5", Img = "nature.jpg", IsFeatured = false, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 },
                        new { Id = 19, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 6", Img = "nature.jpg", IsFeatured = false, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 },
                        new { Id = 20, AuthorId = 1, Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Opinion piece 7", Img = "nature.jpg", IsFeatured = false, Paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore", TitleId = 2 }
                    );
                });

            modelBuilder.Entity("RNN.Models.Post", b =>
                {
                    b.HasBaseType("RNN.Models.Article");


                    b.ToTable("Post");

                    b.HasDiscriminator().HasValue("Post");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 1", IsFeatured = true, Url = "" },
                        new { Id = 2, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 2", IsFeatured = true, Url = "" },
                        new { Id = 3, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 3", IsFeatured = true, Url = "" },
                        new { Id = 4, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 4", IsFeatured = true, Url = "" },
                        new { Id = 5, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 5", IsFeatured = true, Url = "" },
                        new { Id = 6, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 6", IsFeatured = true, Url = "" },
                        new { Id = 7, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 7", IsFeatured = true, Url = "" },
                        new { Id = 8, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 8", IsFeatured = true, Url = "" },
                        new { Id = 9, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 9", IsFeatured = true, Url = "" },
                        new { Id = 10, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 10", IsFeatured = true, Url = "" },
                        new { Id = 11, Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HeadLine = "Test post: put all the content here for the post title 11", IsFeatured = true, Url = "" }
                    );
                });

            modelBuilder.Entity("RNN.Models.Article", b =>
                {
                    b.HasOne("RNN.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("RNN.Models.Grouping", "Grouping")
                        .WithMany()
                        .HasForeignKey("GroupingId");

                    b.HasOne("RNN.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId");
                });

            modelBuilder.Entity("RNN.Models.ArticleToTopic", b =>
                {
                    b.HasOne("RNN.Models.Article", "Article")
                        .WithMany("ArticleToTopics")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RNN.Models.Topic", "Topic")
                        .WithMany("ArticleToTopic")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
